### ISSUE TITLE
Failed run gulp error

### ISSUE THREAD

**Issue by labinformatikaft** [Gaia3D/mago3d#143]
I tried to run gulp but i got error, something like this
![5ae8830638924ae3bee837828c551083](https://user-images.githubusercontent.com/39943058/42556905-438ec564-8517-11e8-99e3-8337824c6790.png)

**Comment by cheonjeongdae** [comment]
* I used Google Translator.

branch: develop
https://github.com/Gaia3D/mago3djs.git
Download the latest sources from.

The above problem is related to devDependencies in package.json.
Recently we worked on changing all gulp plugin version to latest.
An error occurred... eslint, typescript, etc.....  and reverted to the previous version.

After deleting the node_modules of the mago3djs project
After running npm install again
Please run gulp.

**Comment by labinformatikaft** [comment]
It works. thank you very much
